//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alert.Action.SendEmail.MMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://bankofamerica.com/MMS_WebService")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DoNotSendUntilDTSField;
        
        private int ForeignKeyIDField;
        
        private int SourceAppIDField;
        
        private Alert.Action.SendEmail.MMS.MessageStatus StatusField;
        
        private Alert.Action.SendEmail.MMS.MessageType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Alert.Action.SendEmail.MMS.ArrayOfString RecipientCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        private int MessageIdField;
        
        private Alert.Action.SendEmail.MMS.Priority PriorityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DoNotSendUntilDTS {
            get {
                return this.DoNotSendUntilDTSField;
            }
            set {
                if ((this.DoNotSendUntilDTSField.Equals(value) != true)) {
                    this.DoNotSendUntilDTSField = value;
                    this.RaisePropertyChanged("DoNotSendUntilDTS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ForeignKeyID {
            get {
                return this.ForeignKeyIDField;
            }
            set {
                if ((this.ForeignKeyIDField.Equals(value) != true)) {
                    this.ForeignKeyIDField = value;
                    this.RaisePropertyChanged("ForeignKeyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SourceAppID {
            get {
                return this.SourceAppIDField;
            }
            set {
                if ((this.SourceAppIDField.Equals(value) != true)) {
                    this.SourceAppIDField = value;
                    this.RaisePropertyChanged("SourceAppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Alert.Action.SendEmail.MMS.MessageStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Alert.Action.SendEmail.MMS.MessageType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Alert.Action.SendEmail.MMS.ArrayOfString RecipientCollection {
            get {
                return this.RecipientCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientCollectionField, value) != true)) {
                    this.RecipientCollectionField = value;
                    this.RaisePropertyChanged("RecipientCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string FromAddress {
            get {
                return this.FromAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAddressField, value) != true)) {
                    this.FromAddressField = value;
                    this.RaisePropertyChanged("FromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public Alert.Action.SendEmail.MMS.Priority Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageStatus", Namespace="http://bankofamerica.com/MMS_WebService")]
    public enum MessageStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processing = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DoNotSend = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialError = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://bankofamerica.com/MMS_WebService")]
    public enum MessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NetSend = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Communicator = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://bankofamerica.com/MMS_WebService", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Priority", Namespace="http://bankofamerica.com/MMS_WebService")]
    public enum Priority : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medium = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bankofamerica.com/MMS_WebService", ConfigurationName="MMS.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name message from namespace http://bankofamerica.com/MMS_WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bankofamerica.com/MMS_WebService/InsertMessage", ReplyAction="*")]
        Alert.Action.SendEmail.MMS.InsertMessageResponse InsertMessage(Alert.Action.SendEmail.MMS.InsertMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMessage", Namespace="http://bankofamerica.com/MMS_WebService", Order=0)]
        public Alert.Action.SendEmail.MMS.InsertMessageRequestBody Body;
        
        public InsertMessageRequest() {
        }
        
        public InsertMessageRequest(Alert.Action.SendEmail.MMS.InsertMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bankofamerica.com/MMS_WebService")]
    public partial class InsertMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Alert.Action.SendEmail.MMS.Message message;
        
        public InsertMessageRequestBody() {
        }
        
        public InsertMessageRequestBody(Alert.Action.SendEmail.MMS.Message message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMessageResponse", Namespace="http://bankofamerica.com/MMS_WebService", Order=0)]
        public Alert.Action.SendEmail.MMS.InsertMessageResponseBody Body;
        
        public InsertMessageResponse() {
        }
        
        public InsertMessageResponse(Alert.Action.SendEmail.MMS.InsertMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bankofamerica.com/MMS_WebService")]
    public partial class InsertMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertMessageResult;
        
        public InsertMessageResponseBody() {
        }
        
        public InsertMessageResponseBody(int InsertMessageResult) {
            this.InsertMessageResult = InsertMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Alert.Action.SendEmail.MMS.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Alert.Action.SendEmail.MMS.ServiceSoap>, Alert.Action.SendEmail.MMS.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alert.Action.SendEmail.MMS.InsertMessageResponse Alert.Action.SendEmail.MMS.ServiceSoap.InsertMessage(Alert.Action.SendEmail.MMS.InsertMessageRequest request) {
            return base.Channel.InsertMessage(request);
        }
        
        public int InsertMessage(Alert.Action.SendEmail.MMS.Message message) {
            Alert.Action.SendEmail.MMS.InsertMessageRequest inValue = new Alert.Action.SendEmail.MMS.InsertMessageRequest();
            inValue.Body = new Alert.Action.SendEmail.MMS.InsertMessageRequestBody();
            inValue.Body.message = message;
            Alert.Action.SendEmail.MMS.InsertMessageResponse retVal = ((Alert.Action.SendEmail.MMS.ServiceSoap)(this)).InsertMessage(inValue);
            return retVal.Body.InsertMessageResult;
        }
    }
}
